import {useEffect, useState} from 'react';
import type {Review, Decision, Config, Comparison, Presentation} from './types';
import {accessToken, checkedConfig, clearSession, signOut, startSignIn} from './auth';
import './style.css';

const words:Record<string,string>={ALLOW:'Delegate',HUMAN_REVIEW:'Human review',DO_NOT_DELEGATE:'Never delegate',UNKNOWN:'Unconfirmed',REVIEW_REQUIRED:'Review required',OPEN:'Open',NO_DECISION_CHANGE:'No judgment change',REJECTED:'Rejected'};
function Badge({value}:{value:string}){return <span className={'badge '+value.toLowerCase()}>{words[value]||value.replaceAll('_',' ')}</span>;}
function EvidenceRefs({refs}:{refs:string[]}){return <details className="refs"><summary>Source references</summary><ul>{refs.map((r,i)=><li key={i}><code>{r}</code></li>)}</ul></details>;}
function Header({signedIn,onOut}:{signedIn:boolean;onOut:()=>void}){return <header className="masthead"><div className="brand">SOLIFAN <span>READINESSOPS</span></div><div className="workspace-label">AWS workspace</div>{signedIn&&<button className="text-button" onClick={onOut}>Sign out</button>}</header>;}
function Cases({comparison,profile}:{comparison:Comparison;profile:Presentation}){return <div className="table-scroll"><table><caption>Observed agent judgments · same requests, fixed releases</caption><thead><tr><th>Case</th>{profile.columns.map(c=><th key={c.id}>{c.label}</th>)}<th>{comparison.before_release}</th><th>{comparison.candidate_release}</th></tr></thead><tbody>{comparison.cases.map(c=><tr key={c.case_id} className={c.before!==c.candidate?'changed-row':''}><th>{c.case_id}</th>{profile.columns.map(field=><td key={field.id}>{profile.rows[c.case_id]?.[field.id]||'—'}</td>)}<td><Badge value={c.before}/></td><td><Badge value={c.candidate}/></td></tr>)}</tbody></table></div>;}
function download(value:unknown,name:string){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const time=(value:string)=>new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Tokyo'})+' JST';

export function ReviewView({data}:{data:Review}){
  const [tab,setTab]=useState('review'),[decision,setDecision]=useState<Decision>('MAINTAIN');
  const semantic=data.comparisons.semantic,benign=data.comparisons.benign,profile=data.presentation;
  const analysis=semantic.patch.analysis,affected=semantic.patch.affected_case_ids,preview=data.previews[decision],choices=profile.decisions;
  return <section className="review-module">
    <div className="page-heading"><div><p className="eyebrow">AUTHORITY DELTA · HUMAN REVIEW</p><h1>{affected.length===1?'One judgment needs you.':`${affected.length} judgments need review.`}</h1><p className="lead">Compare this saved sample boundary with the observed agent update.</p></div><Badge value="REVIEW_REQUIRED"/></div>
    <nav className="tabs" aria-label="Comparison sections">{[['review','Decision review'],['benign','Unchanged release']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} aria-current={tab===id?'page':undefined}>{label}</button>)}</nav>
    {tab==='review'?<>
      <div className="review-grid"><section className="analysis-panel"><div className="section-top"><h2>What changed</h2><span>{affected.length} of {semantic.cases.length} scenarios</span></div>
        {analysis.changes.map(change=><article key={change.case_id} className="change"><div className="case-heading"><span className="case-id">{change.case_id}</span><strong>{profile.columns.map(f=>profile.rows[change.case_id]?.[f.id]).filter(Boolean).join(' · ')}</strong></div><div className="judgment-pair"><div><span>{semantic.before_release} · previously</span><Badge value={change.before_judgment}/></div><span className="transition" aria-hidden="true">→</span><div><span>{semantic.candidate_release} · candidate</span><Badge value={change.after_judgment}/></div></div><p className="change-reason">{change.reason}</p><div className="definition-change">{change.definition_fields.map(f=><div key={f}><p>{f.replaceAll('_',' ')}</p><div><code>{JSON.stringify(semantic.definitions[semantic.before_release][f])}</code><span>→</span><code>{JSON.stringify(semantic.definitions[semantic.candidate_release][f])}</code></div></div>)}</div><EvidenceRefs refs={change.evidence_refs}/></article>)}
        <div className="boundary-note"><strong>The sample reference boundary stays fixed.</strong><p>{profile.boundary_note}</p></div>
        <details className="analysis-details"><summary>Read the agent’s full explanation</summary><p>{analysis.summary}</p><h3>How to preserve the reference boundary</h3><p>{analysis.maintain_proposal}</p>{analysis.counterexamples.map(c=><div key={c.case_id}><h3>{c.case_id} · unchanged control</h3><p>{c.reason}</p><EvidenceRefs refs={c.evidence_refs}/></div>)}</details>
      </section><aside className="decision-panel"><p className="eyebrow">YOUR DECISION</p><h2>Compare the effects</h2><p className="muted">Choose a boundary to preview its effect on the candidate release.</p><fieldset><legend className="sr-only">Decision preview</legend>{choices.map(c=><label className={'choice '+(decision===c.id?'selected':'')} key={c.id}><input type="radio" name="decision" value={c.id} checked={decision===c.id} onChange={()=>setDecision(c.id)}/><span><strong>{c.title}</strong><small>{c.text}</small></span></label>)}</fieldset><div className="preview-state"><strong>Preview only</strong><p>No approval is recorded and no policy is published by this screen.</p></div></aside></div>
      <section className="panel outcomes"><div className="section-top"><div><p className="eyebrow">BOUNDARY PREVIEW</p><h2>{choices.find(c=>c.id===decision)!.title}</h2></div><span className="prediction-label">Calculated effect · not execution results</span></div><p className="muted">{profile.preview_summaries[decision]}</p><div className="outcome-strip">{preview.expected_outcomes.map(o=><div key={o.case_id} className={'outcome '+o.expected_policy_outcome.toLowerCase()}><strong>{o.case_id}</strong><span>{o.expected_policy_outcome==='ALLOW'?'Would allow':'Would deny'}</span>{data.auxiliary_cases.some(c=>c.case_id===o.case_id)&&<small>Auxiliary control</small>}</div>)}</div></section>
      <section className="panel"><h2>All {semantic.cases.length} observed scenarios</h2><Cases comparison={semantic} profile={profile}/></section>
    </>:<section className="panel benign"><p className="eyebrow">CONTROL COMPARISON · {benign.before_release} → {benign.candidate_release}</p><h2>{benign.patch.affected_case_ids.length===0?'No judgment changed.':'This comparison needs review.'}</h2><p className="lead">{benign.patch.analysis.summary}</p><div className="boundary-note"><strong>No decision requested</strong><p>This comparison does not automatically approve or publish the new release.</p></div><Cases comparison={benign} profile={profile}/></section>}
  </section>;
}

type Section='overview'|'evidence'|'findings'|'review'|'history';
export function WorkspaceView({data,initialSection='overview'}:{data:Review;initialSection?:Section}){
  const [section,setSection]=useState<Section>(initialSection);const w=data.workspace,object=w.objects[0];
  const sections:{id:Section;label:string;count?:number}[]=[{id:'overview',label:'Overview'},{id:'evidence',label:'Evidence',count:w.evidence.length},{id:'findings',label:'Findings & actions',count:w.findings.length},{id:'review',label:'Human review',count:w.actions.filter(a=>a.state==='REVIEW_REQUIRED').length},{id:'history',label:'History'}];
  return <main className="workspace"><aside className="workspace-menu"><p className="eyebrow">READINESSOPS</p><nav aria-label="Workspace sections">{sections.map(s=><button key={s.id} aria-current={section===s.id?'page':undefined} onClick={()=>setSection(s.id)}><span>{s.label}</span>{s.count!==undefined&&<small>{s.count}</small>}</button>)}</nav><div className="workspace-context"><span>AWS environment</span><strong>{data.region}</strong><p>{data.connection_scope}</p></div></aside><div className="workspace-content"><div className="context-line"><span>{object.name}</span>{object.sample&&<span className="sample-mark">Sample workspace</span>}<span className="context-right">{data.comparisons.semantic.before_release} → {data.comparisons.semantic.candidate_release}</span></div>
    {section==='overview'&&<><div className="page-heading"><div><p className="eyebrow">GOVERNANCE OVERVIEW</p><h1>From evidence to decisions.</h1><p className="lead">Understand your AI work, review what changed, and keep the reasons with each decision.</p></div></div><section className="overview-metrics" aria-label="Current workspace status">{[['Managed objects',w.objects.length],['Evidence records',w.evidence.length],['Open findings',w.findings.length],['Human decisions recorded',w.decisions.length]].map(([label,n])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</section>
      <section className="panel"><div className="section-top"><div><p className="eyebrow">MANAGED WORK</p><h2>Business objects & agents</h2></div><Badge value={object.state}/></div>{w.objects.map(o=><div className="object-row" key={o.object_id}><div><h3>{o.name}</h3><p>{o.purpose}</p><span className="muted">{o.sample_label}</span></div><button className="primary" onClick={()=>setSection('review')}>Review changes</button></div>)}</section>
      <div className="overview-grid"><section className="panel"><p className="eyebrow">WHAT NEEDS ATTENTION</p><h2>{w.findings.length===1?'An earlier judgment changed.':`${w.findings.length} findings to review.`}</h2>{w.findings.slice(0,2).map(f=><p key={f.finding_id}>{f.description}</p>)}<button className="inline-action" onClick={()=>setSection('findings')}>Open findings & actions →</button></section><section className="panel"><p className="eyebrow">AUTHORITY DELTA</p><h2>Keep approval tied to the evidence.</h2><p>Compare fixed agent releases against the earlier human judgment. Review the affected decisions with their source evidence.</p><button className="inline-action" onClick={()=>setSection('evidence')}>Inspect the evidence →</button></section></div><p className="workspace-note">This workspace contains observed AWS analysis. Human decision recording and policy publication are pending implementation.</p></>}
    {section==='evidence'&&<><div className="page-heading"><div><p className="eyebrow">EVIDENCE REGISTER</p><h1>Know what supports the review.</h1><p className="lead">Release definitions and observed behavior, imported from a fixed version of the AWS report.</p></div><button className="primary" onClick={()=>download(data,'ReadinessOps_Workspace_Evidence.json')}>Download evidence</button></div>{w.evidence.map(e=><section className="panel evidence-record" key={e.evidence_id}><div className="section-top"><h2>{e.title}</h2><span>{e.kind.replaceAll('_',' ')}</span></div><p className="muted">{object.name}</p><details><summary>View recorded content</summary><pre>{JSON.stringify(e.content,null,2)}</pre></details><details className="refs"><summary>Version & integrity</summary><p><code>{e.content_hash}</code></p><p>Source version: <code>{e.source.version_id}</code></p><p><code>s3://{e.source.bucket}/{e.source.key}</code></p></details></section>)}</>}
    {section==='findings'&&<><div className="page-heading"><div><p className="eyebrow">GAPS, RISKS & ACTIONS</p><h1>Turn findings into a decision.</h1><p className="lead">Each open finding stays connected to its evidence and required action.</p></div></div>{w.findings.map(f=>{const a=w.actions.find(x=>x.action_id===f.action_id)!;return <section className="panel finding" key={f.finding_id}><div className="section-top"><h2>{f.title}</h2><Badge value={f.state}/></div><p className="case-id inline-id">{f.case_id}</p><h3>Gap</h3><p>{f.description}</p><h3>Risk to review</h3><p>{f.risk}</p><div className="action-record"><p className="eyebrow">REQUIRED ACTION</p><h3>{a.title}</h3><p>{a.description}</p><button className="primary" onClick={()=>setSection('review')}>Open human review</button></div><EvidenceRefs refs={f.evidence_refs}/><button className="inline-action" onClick={()=>setSection('evidence')}>View supporting evidence →</button></section>;})}{!w.findings.length&&<section className="panel"><h2>No open findings in this comparison.</h2></section>}</>}
    {section==='review'&&<ReviewView data={data}/>}
    {section==='history'&&<><div className="page-heading"><div><p className="eyebrow">DECISION & PUBLICATION HISTORY</p><h1>Keep the reasoning with the result.</h1><p className="lead">Observed analysis is retained. No human approval or policy publication has been recorded by this workspace.</p></div></div><section className="panel"><h2>Recorded analysis</h2>{w.history.map(e=><article className="history-record" key={e.event_id}><div><strong>{e.label}</strong><Badge value={e.status}/></div><p>{time(e.recorded_at)} · {e.time_basis}</p><details className="refs"><summary>Execution reference</summary><code>{e.request_id}</code></details></article>)}</section><section className="panel"><h2>Human decisions & publications</h2><p className="muted">No decision receipt or publication result yet.</p></section></>}
    <footer>ReadinessOps · AWS edition <span>Evidence → judgment → human review → publication → history</span></footer>
  </div></main>;
}

export default function App(){
  const [config,setConfig]=useState<Config|null>(null),[data,setData]=useState<Review|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;(async()=>{try{
    const r=await fetch('./config.json',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('Workspace configuration is unavailable.');
    const c=checkedConfig(await r.json());if(!active)return;setConfig(c);const token=await accessToken(c);if(!token)return;
    const review=await fetch(c.api_origin+'/review',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.timeout(15000)});
    if(review.status===401){clearSession();throw new Error('Your session expired. Please sign in again.');}
    if(!review.ok)throw new Error(review.status===403?'This account does not have review access.':'Review evidence is temporarily unavailable.');
    const d=await review.json();if(d.mode!=='REVIEW_PREVIEW_ONLY'||d.workspace?.product!=='ReadinessOps'||d.workspace?.schema_version!=='1.1'||!d.presentation?.adapter_id||!d.comparisons?.semantic?.patch?.analysis)throw new Error('The workspace evidence is incomplete.');if(active)setData(d);
  }catch(e){if(active)setError(e instanceof Error?e.message:'The workspace could not be opened.');}finally{if(active)setBusy(false);}})();return()=>{active=false};},[]);
  const login=()=>{if(config)startSignIn(config).catch(()=>setError('Sign-in could not be started.'));};
  return <><Header signedIn={!!data} onOut={()=>config&&signOut(config)}/>{data?<WorkspaceView data={data}/>:<main className="sign-in"><p className="eyebrow">READINESSOPS · AWS EDITION</p><h1>Govern AI work<br/>with evidence.</h1><p className="lead">Connect the evidence, decisions and human judgment behind your AI operations.</p>{busy?<p role="status">Opening your workspace…</p>:<>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={!config} onClick={login}>Open your workspace</button><p className="muted">Sign in with your assigned ReadinessOps reviewer account.</p></>}</main>}</>;
}
