import {build} from 'esbuild';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {renderToStaticMarkup} from 'react-dom/server';import {createElement} from 'react';
await build({entryPoints:['src/BusinessApp.tsx'],bundle:true,packages:'external',loader:{'.css':'empty'},outfile:'.test/business-view.mjs',format:'esm',platform:'node',jsx:'automatic'});await build({entryPoints:['src/business-api.ts'],bundle:true,outfile:'.test/business-api.mjs',format:'esm',platform:'node'});
const {CreateObject,ObjectWorkspace,ReassessmentPanel}=await import('./.test/business-view.mjs'),{BusinessApi,needsBusinessSignIn}=await import('./.test/business-api.mjs');const fixture=JSON.parse(await readFile('.test/business.json','utf8')),checks=[];
function render(state,tab){return renderToStaticMarkup(createElement(ObjectWorkspace,{detail:state,api:{},lang:'en',tab,busy:false,setTab:()=>{},perform:async()=>{},refresh:async()=>{},onError:()=>{}}));}
const form=renderToStaticMarkup(createElement(CreateObject,{lang:'en',busy:false,onCreate:()=>{}}));for(const t of ['Business / initiative name','Question to assess','Responsible person','Goal / measurement (optional)','Create and add evidence'])assert.ok(form.includes(t));assert.ok(!/payment|bank|USD/.test(form));checks.push('business_intake_without_payment_requirement','single_language_product_copy');
for(const [tab,expected] of Object.entries({overview:['THE QUESTION','Your published decision will appear here.','Not applied'],evidence:['Add evidence','Choose file','No file selected','business-file-native','data-sharing.txt','Download original','Text ready'],review:['Save decision draft','Record approval','Return for revision','Record rejection','Publish this decision','Governance','Value','Model routing','Portfolio'],history:['Business object created','Evidence added','Assessment queued','Decision draft saved','Download acceptance evidence']})){const html=render(fixture.approved,tab);for(const t of expected)assert.ok(html.includes(t),tab+': '+t);}checks.push('english_evidence_review_history_render','browser_locale_independent_file_control','four_decision_perspectives','authenticated_acceptance_export_control');
assert.ok(render(fixture.approved,'overview').includes('Your published decision will appear here.'));assert.ok(render(fixture.published,'overview').includes('Local scripted assessment: confirm owner approval'));assert.ok(render(fixture.published,'overview').includes('Not applied'));checks.push('approval_publication_and_runtime_distinct');
const delta=renderToStaticMarkup(createElement(ReassessmentPanel,{proposal:fixture.reassessment_run.analysis.proposal,priorItems:fixture.reassessment_run.comparison_baseline.decision_items,evidence:fixture.reassessment.evidence,lang:'en'}));for(const t of ['AUTHORITY DELTA · CHANGE REVIEW','What changed against the official decision','Official','Candidate','Affected','Unchanged','The official decision has not changed.','no AWS runtime authority is applied'])assert.ok(delta.includes(t),t);assert.ok(delta.indexOf('Affected')<delta.indexOf('Unchanged'));assert.ok(delta.includes(fixture.reassessment_run.comparison_baseline.publication_id));checks.push('reassessment_official_candidate_and_impact_priority');
const attack=structuredClone(fixture.approved);attack.object.question='<script>alert("unsafe")</script>';assert.ok(!render(attack,'overview').includes('<script>'));assert.ok(render(attack,'overview').includes('&lt;script&gt;'));checks.push('untrusted_text_escaped');
const storage=new Map();globalThis.sessionStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};globalThis.location={search:'',origin:'https://dtest.cloudfront.net'};const token='LOCAL.'+btoa(JSON.stringify({scope:'authority-delta/read authority-delta/write authority-delta/approve authority-delta/publish'}))+'.TEST';assert.equal(needsBusinessSignIn(token),false);assert.equal(needsBusinessSignIn('LOCAL.'+btoa(JSON.stringify({scope:'authority-delta/read'}))+'.TEST'),true);checks.push('old_read_only_session_requires_new_scopes');
const config={client_id:'test',auth_origin:'https://authority-delta-test.auth.ap-northeast-1.amazoncognito.com',api_origin:'https://apitest.execute-api.ap-northeast-1.amazonaws.com',redirect_uri:location.origin+'/'};storage.set('authority-delta-session',JSON.stringify({token,expires:Date.now()+600000}));const api=new BusinessApi(config);let firstId,calls=0;
globalThis.fetch=async(url,init)=>{calls++;const body=JSON.parse(init.body);if(!firstId)firstId=body.request_id;else assert.equal(body.request_id,firstId);if(calls===1)throw new Error('Lost after commit');return new Response(JSON.stringify({publication_id:'saved-once'}),{status:200});};
await assert.rejects(api.post('/business/objects/test/publish',{expected_revision:7,receipt_id:'exact'}),/could not be confirmed/);assert.ok(api.hasPending());await assert.rejects(api.post('/business/objects/test/publish',{expected_revision:8,receipt_id:'different'}),/Recover the previous operation/);assert.equal(calls,1);const reconnect=new BusinessApi(config);assert.deepEqual(await reconnect.recover(),{publication_id:'saved-once'});assert.equal(calls,2);assert.equal(reconnect.hasPending(),false);checks.push('lost_response_recovery_same_request_id','pending_write_blocks_different_command','english_recovery_and_pending_errors');
globalThis.fetch=async()=>new Response(JSON.stringify({error:'Stale record',code:'STALE_VERSION'}),{status:409});await assert.rejects(api.post('/business/objects/test/draft',{expected_revision:1}),/Stale/);assert.equal(api.hasPending(),false);checks.push('stale_request_cleared');
globalThis.fetch=async()=>new Response(JSON.stringify({error:'Sign in required',code:'SIGN_IN_REQUIRED'}),{status:401});await assert.rejects(api.post('/business/objects/test/draft',{expected_revision:1}),/Sign in/);assert.ok(api.hasPending());assert.equal(storage.has('authority-delta-session'),false);checks.push('expired_auth_retains_command');
storage.delete('readinessops-pending-command');await assert.rejects(api.get('/business/objects'),/Sign in to continue/);const apiBundle=await readFile('.test/business-api.mjs','utf8');assert.ok(apiBundle.includes('Sign in to continue'));checks.push('sign_in_error','client_error_bundle');
const result={scope:'LOCAL_REACT_RENDER_AND_CLIENT_CONTRACT_NO_BROWSER_OR_LIVE_AWS',result:'PASS',checks};await writeFile('../evidence/local/business-ui-contract.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
